#! /usr/bin/env lua

-- Copyright (c) 2024 <dev@brigid.jp>
-- This software is released under the MIT License.
-- https://opensource.org/licenses/mit-license.php

local brigid = require "brigid"
brigid.dlopen_self()

local unpack = table.unpack or unpack

local homedir = os.getenv "HOME"
local datadir = homedir.."/.brigid-atproto"


local commands = {}

-- https://atproto.com/specs/handle
function commands.save_credentials(identifier, password)




end

os.exit()
local brigid_atproto = require "brigid.atproto"


local IDENTIFIER, PASSWORD = ...

local text = "空き家からもれだして、暗渠を侵食する木々。用賀中学校の北西の交差点、矢沢川は丁字に合流する。流れはいつか、等々力渓谷に至る。"

-- local text = "公式クライアントでURLじゃないリンクを張る方法がわからない。私は煙人計画🤖、URLリンクと違ってワンクッション入る。"
-- local i, j = assert(text:find "煙人計画")
-- local facets = {
--   {
--     index = {
--       byteStart = i - 1;
--       byteEnd = j;
--     };
--     features = {
--       {
--         ["$type"] = "app.bsky.richtext.facet#link";
--         uri = "https://vaporoid.com/";
--       };
--     };
--   };
-- }

local function load_blob(path)
  local handle = assert(io.open(path, "rb"))
  local data = handle:read "*a"
  handle:close()
  return data
end

local photo_path = "/Users/moyu/Desktop/photo.jpg"
local map_path = "/Users/moyu/Desktop/map.jpg"

local photo_data = load_blob(photo_path)
local map_data = load_blob(map_path)

print(#photo_data)
print(#map_data)

local atproto <close> = brigid_atproto("https://bsky.social", "brigid-atproto/0.1")
atproto.debug = true
if not atproto:load_session(IDENTIFIER) then
  assert(atproto:create_session(IDENTIFIER, PASSWORD))
end

-- assert(atproto:get("app.bsky.feed.getTimeline", { limit = 1 }))

local photo = assert(atproto:post_blob("com.atproto.repo.uploadBlob", "image/jpeg", photo_data))
local map = assert(atproto:post_blob("com.atproto.repo.uploadBlob", "image/jpeg", map_data))

assert(atproto:post("com.atproto.repo.createRecord", {
  repo = IDENTIFIER;
  collection = "app.bsky.feed.post";
  record = {
    ["$type"] = "app.bsky.feed.post";
    text = text;
    createdAt = os.date("!%Y-%m-%dT%H:%M:%SZ");
    embed = {
      ["$type"] = "app.bsky.embed.images";
      images = {
        {
          alt = "空き家からもれだして、暗渠を侵食する木々。";
          image = photo.blob;
        };
        {
          alt = "用賀中学校の北西の交差点、矢沢川は丁字に合流する。";
          image = map.blob;
        };
      };
    };
  };
}))

-- assert(atproto:refresh_session())
assert(atproto:delete_session())
