#! /usr/bin/env lua

-- Copyright (c) 2024 <dev@brigid.jp>
-- This software is released under the MIT License.
-- https://opensource.org/licenses/mit-license.php

local brigid = require "brigid"
local brigid_atproto = require "brigid.atproto"

brigid.dlopen_self()

local IDENTIFIER, PASSWORD = ...

local atproto <close> = brigid_atproto("https://bsky.social", "brigid-atproto/0.1")
atproto.debug = true
if not atproto:load_session(IDENTIFIER) then
  assert(atproto:create_session(IDENTIFIER, PASSWORD))
end

assert(atproto:get("app.bsky.feed.getTimeline", { limit = 1 }))
-- assert(atproto:post("com.atproto.repo.createRecord", {
--   repo = IDENTIFIER;
--   collection = "app.bsky.feed.post";
--   record = {
--     ["$type"] = "app.bsky.feed.post";
--     text = "投稿てすと💕";
--     createdAt = os.date("!%Y-%m-%dT%H:%M:%SZ");
--   };
-- }))

-- assert(atproto:refresh_session())
assert(atproto:delete_session())
